spring:
  security:
    user:
      name: none
      password: none
  logging:
    level:
      org.springframework.security: DEBUG
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
    contexts: local
  datasource:
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: very-very-secret-key-must-be-32+chars
encryption:
  salt: eagle-salt