CREATE TABLE ACCOUNTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID VARCHAR(255) NOT NULL UNIQUE,
    USER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
