CREATE TABLE ACCOUNTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID VARCHAR(255) NOT NULL UNIQUE,
    USER_ID VARCHAR(255) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    SORT_CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(10) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
