CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONENUMBER VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    UNIQUE (USER_ID),
    UNIQUE (EMAIL)
);